#ifndef __SETTINGS_H
#define __SETTINGS_H

#define MQTT_RECONNECT_TIMEOUT 5000
#define WIFI_RECONNECT_TIMEOUT 5000

#define MQTT_LOOP_RUN_TIMEOUT 1000
#define APP_INTERVAL 5000
#define APP_MAX_INTERVAL 60000
#define APP_MIN_INTERVAL 1000

#define MQTT_PAYLOAD_MAX_LENGTH 64

#ifndef BUILD_VERSION
#define BUILD_VERSION ""
#endif

#endif